ARG TIMESTAMP
FROM gentoo/stage3:systemd${TIMESTAMP:+-$TIMESTAMP}
ARG GENTOO_MIRRORS
ARG MAKEOPTS
ARG http_proxy
ARG https_proxy
ARG L10N

RUN echo ${GENTOO_MIRRORS:+GENTOO_MIRRORS=$GENTOO_MIRRORS} \
  | tee -a /etc/portage/make.conf
RUN echo MAKEOPTS=${MAKEOPTS:--j16} \
  | tee -a /etc/portage/make.conf
RUN echo ${http_proxy:+http_proxy=$http_proxy} \
  | tee -a /etc/portage/make.conf
RUN echo ${https_proxy:+https_proxy=$https_proxy} \
  | tee -a /etc/portage/make.conf
RUN echo ${L10N:+L10N=$L10N} \
  | tee -a /etc/portage/make.conf
RUN echo ACCEPT_LICENSE=\"-* @FREE linux-fw-redistributable no-source-code\" \
  | tee -a /etc/portage/make.conf

RUN sh -exc "\
  mkdir -vp /etc/portage/repos.conf \
    && cp -v /usr/share/portage/config/repos.conf \
             /etc/portage/repos.conf/gentoo.conf \
    && emerge-webrsync \
"

# continue with image build ...
CMD /bin/bash
